import type { Metadata } from "next";
import "./globals.css";
import AppProvider from "./AppProvider";
import { PythPriceProvider } from "@/contexts/pythPrice";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AppProvider>
          <PythPriceProvider>{children}</PythPriceProvider>
        </AppProvider>
      </body>
    </html>
  );
}
