[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
stable_coin = "5TVQ83cMtsw2cGoHoGBxMjoo57UhFh2MVXGh5J2pzia1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "../my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 ./stable_coin/test/test.tests.ts"
